apiVersion: v1
kind: Service
metadata:
  name: nodejslab-service
spec:
  type: ClusterIP # тип доступу до сервісу, ClusterIp - значення за замовчуванням і може бути пропущене
  selector:
    app: nodejslab # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу
  ports:
  - port: 8080  # порт по якому можна звератись до сервісу
    targetPort: 80 # порт контейнера
