name: Lint, build and push to DockerHub
on:
  push:
      branches: [ "master" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Install eslint
       run: npm i eslint
     - name: Run eslint #checking nodejs app
       run: node_modules/eslint/bin/eslint.js 
     - name: Check out code Dockerfile
       uses: actions/checkout@v1
     - name: Run hadolint for Dockerfile 
       uses: reviewdog/action-hadolint@v1
       with:
           github_token: ${{ secrets.github_token }}
           hadolint_ignore: DL3008
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/node-app:v1 .
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{secrets.DOCKERHUB_USERNAME}}/node-app:v1
          push: true
